_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
#    NUM_CLASSES: 21 # 0-19 Known class; 20 -> Unknown; 21 -> Background.
     NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:

  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  STEPS: (27000, 30000)
  MAX_ITER: 46000  # 17.4 epochs
#  STEPS: (12000, 16000)
#  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/baseline_run"
OWOD:
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  NUM_UNK_PER_IMAGE: 1
  ENABLE_UNCERTAINITY_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: False
  CLUSTERING:
    ITEMS_PER_CLASS: 20
    START_ITER: 20
    UPDATE_MU_ITER: 3000
    MOMENTUM: 0.99
    Z_DIMENSION: 128 # 64 128 is also 3.5 h

#  CLUSTERING:
#    ITEMS_PER_CLASS: 20
#    START_ITER: 1000
#    UPDATE_MU_ITER: 3000
#    MOMENTUM: 0.99
